pipeline {

    agent any

    environment {

        DOCKERHUB_CREDENTIALS = 'dockerhub-creds'

        FRONTEND_IMAGE = 'mrunali2010/nadsoft-frontend'

        BACKEND_IMAGE = 'mrunali2010/nadsoft-backend'

        K8S_NAMESPACE = 'nadsoft'
    }

    stages {

        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Clone Repository') {
            steps {

                git branch: 'main',
                url: 'https://github.com/mrunali20raut/P-NADSOFT-PROJECT.git'
            }
        }

        stage('Debug Workspace') {
    steps {
        sh 'ls -R'
    }
}

        stage('Build Backend Docker Image') {
            steps {
                dir('nadsoft-full-stack') {
                sh 'docker build -t $BACKEND_IMAGE:v1 ./nadsoft-backend'
                
                }
            }
        }

        stage('Build Frontend Docker Image') {
            steps {

                dir('nadsoft-full-stack') {
                sh 'docker build -t $FRONTEND_IMAGE:v1 ./nadsoft-frontend'
               
                }
            }
        }

        stage('DockerHub Login') {
            steps {

                withCredentials([usernamePassword(
                    credentialsId: "${DOCKERHUB_CREDENTIALS}",
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {

                    sh '''
                    echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                    '''
                }
            }
        }

        stage('Push Backend Docker Image') {
            steps {

                sh '''
                docker push $BACKEND_IMAGE:v1
                '''
            }
        }

        stage('Push Frontend Docker Image') {
            steps {

                sh '''
                docker push $FRONTEND_IMAGE:v1
                '''
            }
        }

        stage('Deploy To Kubernetes') {
            steps {

                sh '''
                kubectl apply -f k8/

                kubectl rollout restart deployment backend-deployment -n $K8S_NAMESPACE

                kubectl rollout restart deployment frontend-deployment -n $K8S_NAMESPACE
                '''
            }
        }

        stage('Verify Deployment') {
            steps {

                sh '''
                kubectl get pods -n $K8S_NAMESPACE
                kubectl get svc -n $K8S_NAMESPACE
                '''
            }
        }
    }

    post {

        success {

            echo 'CI/CD Pipeline Executed Successfully!'
        }

        failure {

            echo 'Pipeline Failed!'
        }
    }
}