apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment
  namespace: nadsoft

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend

        image: pranav7820/nadsoft-backend:latest

        ports:
        - containerPort: 5000

        env:
        - name: DB_HOST
          value: nadsoft-mysql.cxqaowkkep9x.ap-south-1.rds.amazonaws.com

        - name: DB_PORT
          value: "3306"

        - name: DB_USER
          value: root

        - name: DB_PASSWORD
          value: admin

        - name: DB_NAME
          value: nadsoft